### ISSUE TITLE
When combo box is smaller the buttons are not equal width

### ISSUE THREAD

**Issue by komitoff** [vaadin-component-factory/multiselect-combo-box#22]
Hello,

While using this multiselect-combo-box I've noticed when the component is smaller (even in the demo), the width of the buttons is different. I've created a pull request with a small improvement for this. Also applied a margin to have some space between the buttons and the overlay layout. Here is a link to the pull request:
[pull request](https://github.com/vaadin-component-factory/multiselect-combo-box/pull/21)

Greetings

**Comment by jcgueriaud1** [comment]
Closed by #21
