### ISSUE TITLE
Doesn't seem to work with Vaadin 14 nor 23

### ISSUE THREAD

**Issue by Hayo-Baan** [vaadin-component-factory/multiselect-combo-box#27]
I can't seem to get the multi combobox component to work at all. With Vaadin 14 I get an error (in the top right corner of the browser) stating that $0.renderLabel is not a function. With Vaadin 23 there is some more information (i.e. there is some error log info), but it boils down to the same problem. Due to the error, the component isn't drawn at all on-screen.

I've created a small demo app that exhibits this issue. You can build and run it with `mvn spring-boot:run`.

Note: I'm trying out MultiComboBox hoping to be able to replace Goran Atanasovski's [MultiselectComboBox](https://vaadin.com/directory/component/multiselect-combo-box) since he has limited time to be able to fix the issues that component has under Vaadin 23.
It's use is included in the demo. Interestingly enough though, that component now also doesn't work any longer, though it works (with some issues) in other apps...

Hopefully it's a simple thing I'm missing in my configuration.

[bug.zip](https://github.com/vaadin-component-factory/multiselect-combo-box/files/8778332/bug.zip)

**Comment by vuyko23** [comment]
Hello.
Also have the same issue. If two projects with the same version of vaadin in one it can work, and in another not. So I think it not because of vaadin version.

**Comment by vuyko23** [comment]
I found a solution that works for me. Make sure you add com.vaadin.componentfactory.multiselect to your whitelist

**Comment by Hayo-Baan** [comment]
@vuyko23, I had com.vaadin.componentfactory in the whitelist so I wanted to try your suggestion and explicitly whitelist com.vaadin.componentfactory.multiselect. But when I now try to compile my bug example code, building the frontend fails regardless of the whitelisting I choose.
The compile error is:
```
------------------ Starting Frontend compilation. ------------------
2022-06-17 09:12:56.474  INFO 5417 --- [onPool-worker-2] c.v.b.devserver.AbstractDevServerRunner  : Running Webpack to compile frontend resources. This may take a moment, please stand by...
2022-06-17 09:12:57.967  INFO 5417 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : [webpack-cli] TypeError: cli.isMultipleCompiler is not a function
2022-06-17 09:12:57.967  INFO 5417 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at Command.<anonymous> (/Users/xxx/Bug/node_modules/@webpack-cli/serve/lib/index.js:146:35)
2022-06-17 09:12:57.967  INFO 5417 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at async Promise.all (index 1)
2022-06-17 09:12:57.968  INFO 5417 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at async Command.<anonymous> (/Users/xxx/Bug/node_modules/webpack-cli/lib/webpack-cli.js:1674:7)

------------------ Frontend compilation failed. ------------------
```

**Comment by jcgueriaud1** [comment]
@HayoBaanAtHand this error "cli.isMultipleCompiler is not a function" is not related to the component. You should update the Vaadin version to [V23.1.1](https://github.com/vaadin/platform/releases/tag/23.1.1), [V23.0.12](https://github.com/vaadin/platform/releases/tag/23.0.12) or [V22.0.17](https://github.com/vaadin/platform/releases/tag/22.0.17).
See here for more details  https://github.com/vaadin/flow/issues/13952#issuecomment-1154825683

**Comment by Hayo-Baan** [comment]
@jcgueriaud1 Awesome! Got it back to compile and run, just my luck to run into a bug in the Vaadin release at this time! 🙃

Better yet, after some experimenting, I found what was causing the problem: instead of a whitespace delimited list, `vaadin.whitelisted-packages` is comma separated 🙄

As all is working, I'll close the issue.
